name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      TARGET_DIR: release-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x 
          
      - name: Build and Publish
        run: |
          dotnet publish Smake.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true -o ${{ env.TARGET_DIR }}
      
      - name: Copy required folders (Languages, Sounds, Jsons)
        shell: powershell
        run: |
          $TargetDir = "${{ env.TARGET_DIR }}" 
          
          Copy-Item -Path "Benoetigtedaten/Languages" -Destination $TargetDir -Recurse
          Copy-Item -Path "Benoetigtedaten/Sounds" -Destination $TargetDir -Recurse
          Copy-Item -Path "Benoetigtedaten/Jsons" -Destination $TargetDir -Recurse
        
      - name: Package Executable and Assets
        run: |
          cd ${{ env.TARGET_DIR }}
          7z a -tzip Smake.zip Smake.exe Languages Sounds Jsons
          
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          files: |
            ${{ env.TARGET_DIR }}/Smake.zip