name: Cross-Platform Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win-x64
            executable_name: Smake.exe
            zip_name: Smake-Windows
          - os: ubuntu-latest
            runtime: linux-x64
            executable_name: Smake
            zip_name: Smake-Linux

    name: Build (${{ matrix.runtime }})
    env:
      TARGET_DIR: release-build

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x

      - run: |
          dotnet publish Smake.csproj -c Release -r ${{ matrix.runtime }} --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true -o ${{ env.TARGET_DIR }}
          
      - run: |
          cp -r Benoetigtedaten/Languages ${{ env.TARGET_DIR }}/
          cp -r Benoetigtedaten/Sounds ${{ env.TARGET_DIR }}/
          cp -r Benoetigtedaten/Jsons ${{ env.TARGET_DIR }}/

      - run: |
          cd ${{ env.TARGET_DIR }}
          7z a -tzip ${{ matrix.zip_name }}-${{ github.ref_name }}.zip ${{ matrix.executable_name }} Languages Sounds Jsons
          
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.zip_name }}-${{ github.ref_name }}
          path: ${{ env.TARGET_DIR }}/${{ matrix.zip_name }}-${{ github.ref_name }}.zip

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts 

      - run: |
          mv artifacts/*.zip .
          
      - run: ls -l
          
      - id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Smake ${{ github.ref_name }} (Cross-Platform)
          draft: true
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          files: |
            Smake-Windows-${{ github.ref_name }}.zip
            Smake-Linux-${{ github.ref_name }}.zip