name: Cross-Platform Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    name: Build Windows
    runs-on: ubuntu-latest
    env:
      WINDOWS_ZIP: Smake-Windows-${{ github.ref_name }}.zip
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install 7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Build & Copy Assets
        run: |
          dotnet publish Smake.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:IncludeNativeLibrariesForSelfExtract=true -o ./Build
          cp -r Benoetigtedaten/Languages ./Build/
          cp -r Benoetigtedaten/Sounds ./Build/
          cp -r Benoetigtedaten/Jsons ./Build/

      - name: Package
        run: |
          cd ./Build
          7z a -tzip ../${{ env.WINDOWS_ZIP }} Smake.exe Languages Sounds Jsons

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-zip
          path: ${{ env.WINDOWS_ZIP }}

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    env:
      LINUX_ZIP: Smake-Linux-${{ github.ref_name }}.zip
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install 7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Build & Copy Assets
        run: |
          dotnet publish Smake.csproj -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:IncludeNativeLibrariesForSelfExtract=true -o ./Build
          cp -r Benoetigtedaten/Languages ./Build/
          cp -r Benoetigtedaten/Sounds ./Build/
          cp -r Benoetigtedaten/Jsons ./Build/

      - name: Package
        run: |
          cd ./Build
          chmod +x Smake
          7z a -tzip ../${{ env.LINUX_ZIP }} Smake Languages Sounds Jsons

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: linux-zip
          path: ${{ env.LINUX_ZIP }}

  build-macos-x86_64:
    name: Build macOS (x86_64)
    runs-on: ubuntu-latest
    env:
      MACOS_X86_64_ZIP: Smake-MacOS-x86_64-${{ github.ref_name }}.zip
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install 7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Build & Copy Assets
        run: |
          dotnet publish Smake.csproj -c Release -r osx-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:IncludeNativeLibrariesForSelfExtract=true -o ./Build
          cp -r Benoetigtedaten/Languages ./Build/
          cp -r Benoetigtedaten/Sounds ./Build/
          cp -r Benoetigtedaten/Jsons ./Build/

      - name: Package
        run: |
          cd ./Build
          chmod +x Smake
          7z a -tzip ../${{ env.MACOS_X86_64_ZIP }} Smake Languages Sounds Jsons

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: macos-x86_64-zip
          path: ${{ env.MACOS_X86_64_ZIP }}

  build-macos-arm:
    name: Build macOS (ARM)
    runs-on: ubuntu-latest
    env:
      MACOS_ARM_ZIP: Smake-MacOS-ARM-${{ github.ref_name }}.zip
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install 7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Build & Copy Assets
        run: |
          dotnet publish Smake.csproj -c Release -r osx-arm64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:IncludeNativeLibrariesForSelfExtract=true -o ./Build
          cp -r Benoetigtedaten/Languages ./Build/
          cp -r Benoetigtedaten/Sounds ./Build/
          cp -r Benoetigtedaten/Jsons ./Build/

      - name: Package
        run: |
          cd ./Build
          chmod +x Smake
          7z a -tzip ../${{ env.MACOS_ARM_ZIP }} Smake Languages Sounds Jsons

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: macos-arm-zip
          path: ${{ env.MACOS_ARM_ZIP }}

  release:
    name: Create Release & Upload Assets
    needs: [build-windows, build-linux, build-macos-x86_64, build-macos-arm]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Download Windows Artifact
        uses: actions/download-artifact@v8
        with:
          name: windows-zip

      - name: Download Linux Artifact
        uses: actions/download-artifact@v8
        with:
          name: linux-zip

      - name: Download macOS x86_64 Artifact
        uses: actions/download-artifact@v8
        with:
          name: macos-x86_64-zip

      - name: Download macOS ARM Artifact
        uses: actions/download-artifact@v8
        with:
          name: macos-arm-zip

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Smake ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          files: |
            Smake-Windows-${{ github.ref_name }}.zip
            Smake-Linux-${{ github.ref_name }}.zip
            Smake-MacOS-x86_64-${{ github.ref_name }}.zip
            Smake-MacOS-ARM-${{ github.ref_name }}.zip
